# Verify status of KVM and VT
- include: kvm-vt.yml
# Verify gtest exists
- include: gtest.yml
# Verify bear exists
- include: bear.yml
# Download and build libwebsockets if needed
- include: libwebsockets.yml
# Download and build qt3 if needed
- include: qt3.yml
