# Cleanup previous executions on this host
- include: qemu_stop.yml

- block:

  - include: hda_image.yml
  - include: qemu_prepare.yml
  when:  prepare_image
- include: qemu_start.yml
  when: activate_instance
